# Generated by Django 4.2.7 on 2024-12-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="age",
            field=models.IntegerField(default=0),
        ),
    ]
