# Generated by Django 4.2.7 on 2024-12-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_systemuser_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemuser",
            name="age",
        ),
        migrations.AddField(
            model_name="systemuser",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
