# Generated by Django 4.2.7 on 2024-12-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_department_rendezvous"),
    ]

    operations = [
        migrations.AddField(
            model_name="rendezvous",
            name="file_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
